import type { AppPreferences } from "../backendTypes";
import type { ActionDef, KeymapAction, KeymapCategory } from "./types";

export const KEYMAP_STORAGE_KEY = "arris.keymap.shortcuts";

export const ACTIONS = {
  runQuery: { label: "Run Query", category: "editor", defaultShortcut: { key: "Mod-Enter" } },
  stopQuery: { label: "Stop Query", category: "editor", defaultShortcut: null },
  toggleLineComment: { label: "Toggle Line Comment", category: "editor", defaultShortcut: { key: "Mod-/" } },
  reformatCode: { label: "Reformat Code", category: "editor", defaultShortcut: { key: "Mod-Alt-l" } },
  findInEditor: { label: "Find in Editor", category: "editor", defaultShortcut: { key: "Mod-f" } },
  replaceInEditor: { label: "Find & Replace in Editor", category: "editor", defaultShortcut: { key: "Mod-r" } },
  saveFile: { label: "Save File", category: "editor", defaultShortcut: { key: "Mod-s" } },
  aiGenerate: { label: "Ask Agent", category: "editor", defaultShortcut: { key: "Mod-k" } },
  expandStar: { label: "Expand All Columns", category: "editor", defaultShortcut: null },
  pinQuery: { label: "Pin Query", category: "editor", defaultShortcut: null },
  openEditorContextMenu: { label: "Open Editor Menu", category: "editor", defaultShortcut: { key: "Alt-Enter" } },
  switchMongoSqlMode: { label: "MongoDB: SQL Mode", category: "editor", defaultShortcut: null },
  switchMongoShellMode: { label: "MongoDB: Shell Mode", category: "editor", defaultShortcut: null },
  switchEsSqlMode: { label: "Elasticsearch: SQL Mode", category: "editor", defaultShortcut: null },
  switchEsRestMode: { label: "Elasticsearch: REST Mode", category: "editor", defaultShortcut: null },
  switchRedisSqlMode: { label: "Redis: SQL Mode", category: "editor", defaultShortcut: null },
  switchRedisCliMode: { label: "Redis: CLI Mode", category: "editor", defaultShortcut: null },

  openTab: { label: "New Query Console", category: "tabs", defaultShortcut: { key: "Mod-t" } },
  closeTab: { label: "Close Tab", category: "tabs", defaultShortcut: { key: "Mod-w" } },
  switchTab: { label: "Switch Tab", category: "tabs", defaultShortcut: { key: "Mod-Tab" } },
  splitRight: { label: "Split Editor Right", category: "tabs", defaultShortcut: null },
  splitLeft: { label: "Split Editor Left", category: "tabs", defaultShortcut: null },
  splitTop: { label: "Split Editor Top", category: "tabs", defaultShortcut: null },
  splitBottom: { label: "Split Editor Bottom", category: "tabs", defaultShortcut: null },
  newTerminalTab: { label: "New Terminal", category: "tabs", defaultShortcut: { key: "Ctrl-Mod-t" } },
  newNotebookTab: { label: "New Jupyter Notebook", category: "tabs", defaultShortcut: { key: "Ctrl-Mod-j" } },
  newCanvasTab: { label: "New Canvas", category: "tabs", defaultShortcut: { key: "Ctrl-Mod-c" } },
  runCellAndInsertBelow: { label: "Run Cell and Insert Below", category: "tabs", defaultShortcut: { key: "Shift-Enter" } },

  canvasMoveTool: { label: "Canvas: Move Tool", category: "canvas", defaultShortcut: { key: "v" } },
  canvasHandTool: { label: "Canvas: Hand Tool", category: "canvas", defaultShortcut: { key: "h" } },
  canvasAddSqlCell: { label: "Canvas: Add SQL Cell", category: "canvas", defaultShortcut: { key: "/" } },
  canvasAddRectangle: { label: "Canvas: Add Rectangle", category: "canvas", defaultShortcut: { key: "r" } },
  canvasAddEllipse: { label: "Canvas: Add Ellipse", category: "canvas", defaultShortcut: { key: "o" } },
  canvasAddLine: { label: "Canvas: Add Line", category: "canvas", defaultShortcut: { key: "l" } },
  canvasBringToFront: { label: "Canvas: Bring to Front", category: "canvas", defaultShortcut: { key: "]" } },
  canvasSendToBack: { label: "Canvas: Send to Back", category: "canvas", defaultShortcut: { key: "[" } },

  openSettings: { label: "Open Settings", category: "navigation", defaultShortcut: { key: "Mod-," } },
  searchFiles: { label: "Search Files", category: "navigation", defaultShortcut: { key: "Mod-p" } },
  searchContent: { label: "Search Content", category: "navigation", defaultShortcut: { key: "Mod-Shift-f" } },
  openProject: { label: "Open Project", category: "navigation", defaultShortcut: { key: "Mod-o" } },

  toggleSidebar: { label: "Toggle Sidebar", category: "sidebar", defaultShortcut: { key: "Mod-Shift-s" } },
  showDefinition: { label: "Show Definition", category: "sidebar", defaultShortcut: { key: "Mod-b" } },
  showAgentPanel: { label: "Show Agent", category: "sidebar", defaultShortcut: { key: "Mod-8" } },
  showProjectPane: { label: "Show Project", category: "sidebar", defaultShortcut: { key: "Mod-1" } },
  showGitPane: { label: "Show Git", category: "sidebar", defaultShortcut: { key: "Mod-2" } },
  showChartEditor: { label: "Show Chart Editor", category: "sidebar", defaultShortcut: { key: "Mod-7" } },
  showPinnedQueries: { label: "Show Pinned Queries", category: "sidebar", defaultShortcut: { key: "Mod-9" } },
  showConnections: { label: "Show Connections", category: "sidebar", defaultShortcut: { key: "Mod-0" } },
  refreshSchema: { label: "Refresh Schema", category: "sidebar", defaultShortcut: null },

  exportCsv: { label: "Export CSV", category: "results", defaultShortcut: null },
  exportJson: { label: "Export JSON", category: "results", defaultShortcut: null },
  toggleTerminal: { label: "Toggle Terminal", category: "results", defaultShortcut: { key: "Ctrl-`" } },
  rerunQuery: { label: "Re-run Query", category: "results", defaultShortcut: null },
  showTableView: { label: "Show Table View", category: "results", defaultShortcut: null },
  showChartView: { label: "Show Chart View", category: "results", defaultShortcut: null },
  toggleExecutionPlan: { label: "Toggle Execution Plan", category: "results", defaultShortcut: null },
  toggleRowDetail: { label: "Toggle Row Detail (JSON)", category: "results", defaultShortcut: null },
  toggleQueryText: { label: "Toggle Query Text", category: "results", defaultShortcut: null },
  toggleFilterRow: { label: "Toggle Filter Row", category: "results", defaultShortcut: null },
  previousPage: { label: "Previous Page", category: "results", defaultShortcut: null },
  nextPage: { label: "Next Page", category: "results", defaultShortcut: null },

  insertRow: { label: "Insert Row", category: "edit", defaultShortcut: null },
  deleteRow: { label: "Delete Selected Row", category: "edit", defaultShortcut: null },
  resetEdits: { label: "Reset Staged Edits", category: "edit", defaultShortcut: null },
  uploadChanges: { label: "Upload Staged Changes", category: "edit", defaultShortcut: null },

  gitStageAll: { label: "Git: Stage All", category: "git", defaultShortcut: null },
  gitUnstageAll: { label: "Git: Unstage All", category: "git", defaultShortcut: null },
  gitCommit: { label: "Git: Commit", category: "git", defaultShortcut: null },
  gitPush: { label: "Git: Push", category: "git", defaultShortcut: null },
  gitFetch: { label: "Git: Fetch", category: "git", defaultShortcut: null },
  gitPull: { label: "Git: Pull", category: "git", defaultShortcut: null },
  gitShowHistory: { label: "Git: Show History", category: "git", defaultShortcut: null },
  gitResolveConflicts: { label: "Git: Resolve Conflicts", category: "git", defaultShortcut: null },

  dbtRun: { label: "dbt Run", category: "dbt", defaultShortcut: { key: "Mod-Shift-r" } },
  dbtTest: { label: "dbt Test", category: "dbt", defaultShortcut: { key: "Mod-Shift-t" } },
  dbtBuild: { label: "dbt Build", category: "dbt", defaultShortcut: { key: "Mod-Shift-b" } },
  dbtCompile: { label: "dbt Compile", category: "dbt", defaultShortcut: { key: "Mod-Shift-e" } },
  dbtDocs: { label: "dbt Docs", category: "dbt", defaultShortcut: { key: "Mod-Shift-d" } },
  dbtLineage: { label: "dbt Lineage", category: "dbt", defaultShortcut: { key: "Mod-Shift-l" } },
  dbtPreview: { label: "dbt Preview", category: "dbt", defaultShortcut: { key: "Mod-Shift-p" } },
  dbtDiff: { label: "dbt Diff", category: "dbt", defaultShortcut: { key: "Mod-Shift-i" } },

  sqlmeshPlan: { label: "SQLMesh Plan", category: "sqlmesh", defaultShortcut: { key: "Mod-Alt-p" } },
  sqlmeshRun: { label: "SQLMesh Run", category: "sqlmesh", defaultShortcut: { key: "Mod-Alt-u" } },
  sqlmeshTest: { label: "SQLMesh Test", category: "sqlmesh", defaultShortcut: { key: "Mod-Alt-t" } },
  sqlmeshRender: { label: "SQLMesh Render", category: "sqlmesh", defaultShortcut: { key: "Mod-Alt-r" } },
  sqlmeshLint: { label: "SQLMesh Lint", category: "sqlmesh", defaultShortcut: { key: "Mod-Alt-i" } },
  sqlmeshAudit: { label: "SQLMesh Audit", category: "sqlmesh", defaultShortcut: { key: "Mod-Alt-a" } },
  sqlmeshLineage: { label: "SQLMesh Lineage", category: "sqlmesh", defaultShortcut: { key: "Mod-Alt-g" } },
  sqlmeshPreview: { label: "SQLMesh Preview", category: "sqlmesh", defaultShortcut: { key: "Mod-Alt-v" } },
} as const satisfies Record<string, ActionDef>;

export const ACTION_ORDER = Object.keys(ACTIONS) as KeymapAction[];

export const CATEGORY_ORDER: KeymapCategory[] = [
  "editor",
  "tabs",
  "canvas",
  "navigation",
  "sidebar",
  "results",
  "edit",
  "git",
  "dbt",
  "sqlmesh",
];

export const CATEGORY_LABELS: Record<KeymapCategory, string> = {
  editor: "Editor",
  tabs: "Tabs",
  canvas: "Canvas",
  navigation: "Navigation",
  sidebar: "Sidebar",
  results: "Results",
  edit: "Table Editing",
  git: "Git",
  dbt: "dbt",
  sqlmesh: "SQLMesh",
};

export const CATEGORY_DESCRIPTIONS: Record<KeymapCategory, string> = {
  editor: "Shortcuts while writing in the SQL and code editor",
  tabs: "Open, close, and arrange editor tabs and splits",
  canvas: "Tools and object actions while working on a canvas board",
  navigation: "Move around the app and open things quickly",
  sidebar: "Toggle and focus the sidebar panes",
  results: "Work with query results, views, and exports",
  edit: "Stage and apply edits to table rows",
  git: "Stage, commit, and sync changes with Git",
  dbt: "Run dbt commands and open its views",
  sqlmesh: "Run SQLMesh commands and open its views",
};

export const preferenceDefaults: AppPreferences = {
  theme: "neon",
  sidebarLeftTab: "files",
  editorFontSize: 13,
  editorFontFamily: null,
  editorColorScheme: "oneDark",
  syntaxOverrides: {},
  indentGuides: true,
  statementBorder: false,
  uiFontFamily: null,
  uiFontSize: 14,
  iconSize: 14,
  showRowDetailPane: false,
  sidebarLeftVisible: true,
  sidebarRightVisible: true,
  bottomPaneVisible: false,
  reopenLastProject: true,
  autosave: true,
  terminalShell: "",
  terminalFontSize: 13,
  terminalFontFamily: null,
  connectionAutoRefreshMs: 0,
  debugMode: false,
  // Mirrors the Rust DEFAULT_SKIP_DIRS seed; the loaded backend value wins, this
  // is only the fallback before preferences hydrate.
  fileTreeSkipDirs: [
    ".git",
    "node_modules",
    "target",
    "dist",
    "build",
    "__pycache__",
    ".venv",
    "venv",
    ".idea",
    ".vscode",
    ".DS_Store",
    ".pytest_cache",
    ".mypy_cache",
    ".dbt",
    "logs",
  ],
  formatter: {
    sql: {
      keywordCase: "upper",
      identifierCase: "preserve",
      dataTypeCase: "preserve",
      functionCase: "preserve",
      indentStyle: "standard",
      tabWidth: 2,
      useTabs: false,
      logicalOperatorNewline: "before",
      expressionWidth: 50,
      linesBetweenQueries: 2,
      denseOperators: false,
      newlineBeforeSemicolon: false,
      commaPosition: "trailing",
    },
    python: {
      indentWidth: 4,
      maxBlankLines: 2,
      trimTrailingWhitespace: true,
    },
    json: {
      indentWidth: 2,
      useTabs: false,
      sortKeys: false,
    },
    yaml: {
      indentWidth: 2,
    },
    csv: {
      delimiter: "comma",
      trimFields: true,
      quoteAllFields: false,
    },
    markdown: {
      listMarker: "dash",
      trimTrailingWhitespace: true,
    },
  },
};
